/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MemorialRouteImport } from './routes/memorial'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedOldQuizzesRouteImport } from './routes/_authenticated/old-quizzes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminUploadQuizRouteImport } from './routes/_authenticated/_admin/upload-quiz'
import { Route as AuthenticatedAdminExportScoresRouteImport } from './routes/_authenticated/_admin/export-scores'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialRoute = MemorialRouteImport.update({
  id: '/memorial',
  path: '/memorial',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOldQuizzesRoute = AuthenticatedOldQuizzesRouteImport.update({
  id: '/old-quizzes',
  path: '/old-quizzes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUploadQuizRoute =
  AuthenticatedAdminUploadQuizRouteImport.update({
    id: '/upload-quiz',
    path: '/upload-quiz',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExportScoresRoute =
  AuthenticatedAdminExportScoresRouteImport.update({
    id: '/export-scores',
    path: '/export-scores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/memorial': typeof MemorialRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/old-quizzes': typeof AuthenticatedOldQuizzesRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/export-scores': typeof AuthenticatedAdminExportScoresRoute
  '/upload-quiz': typeof AuthenticatedAdminUploadQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/memorial': typeof MemorialRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/old-quizzes': typeof AuthenticatedOldQuizzesRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/export-scores': typeof AuthenticatedAdminExportScoresRoute
  '/upload-quiz': typeof AuthenticatedAdminUploadQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/memorial': typeof MemorialRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/old-quizzes': typeof AuthenticatedOldQuizzesRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/export-scores': typeof AuthenticatedAdminExportScoresRoute
  '/_authenticated/_admin/upload-quiz': typeof AuthenticatedAdminUploadQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/memorial'
    | '/register'
    | '/reset-password'
    | '/old-quizzes'
    | '/quiz'
    | '/admin'
    | '/export-scores'
    | '/upload-quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/memorial'
    | '/register'
    | '/reset-password'
    | '/old-quizzes'
    | '/quiz'
    | '/admin'
    | '/export-scores'
    | '/upload-quiz'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/memorial'
    | '/register'
    | '/reset-password'
    | '/_authenticated/_admin'
    | '/_authenticated/old-quizzes'
    | '/_authenticated/quiz'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/export-scores'
    | '/_authenticated/_admin/upload-quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemorialRoute: typeof MemorialRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial': {
      id: '/memorial'
      path: '/memorial'
      fullPath: '/memorial'
      preLoaderRoute: typeof MemorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/old-quizzes': {
      id: '/_authenticated/old-quizzes'
      path: '/old-quizzes'
      fullPath: '/old-quizzes'
      preLoaderRoute: typeof AuthenticatedOldQuizzesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/upload-quiz': {
      id: '/_authenticated/_admin/upload-quiz'
      path: '/upload-quiz'
      fullPath: '/upload-quiz'
      preLoaderRoute: typeof AuthenticatedAdminUploadQuizRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/export-scores': {
      id: '/_authenticated/_admin/export-scores'
      path: '/export-scores'
      fullPath: '/export-scores'
      preLoaderRoute: typeof AuthenticatedAdminExportScoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminExportScoresRoute: typeof AuthenticatedAdminExportScoresRoute
  AuthenticatedAdminUploadQuizRoute: typeof AuthenticatedAdminUploadQuizRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminExportScoresRoute: AuthenticatedAdminExportScoresRoute,
  AuthenticatedAdminUploadQuizRoute: AuthenticatedAdminUploadQuizRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedOldQuizzesRoute: typeof AuthenticatedOldQuizzesRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedOldQuizzesRoute: AuthenticatedOldQuizzesRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MemorialRoute: MemorialRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
